// Seeds artworks that are ready to screen, so a demo does not depend on S3.
//
//   node src/scripts/demo-seed.js [owner-email]
//
// The upload endpoint (POST /api/artwork) pushes bytes to S3 via CDNFileService, which needs
// AWS credentials and a bucket. Screening itself does not: image.loader falls back to a plain HTTP
// fetch when S3_BUCKET_NAME is unset, so an artwork whose file_url is any public image URL screens
// end to end with no object storage at all.
//
// Creates three artworks that exercise the three interesting outcomes under the mock adapters,
// which key off the title.
// Set before ../config loads, so the pool's per-acquire chatter doesn't bury the seeded ids.
process.env.DB_QUIET = process.env.DB_QUIET ?? "true";

require("dotenv").config({ quiet: true });

const { sql } = require("kysely");
const { db } = require("../config");
const { resolveRuleset, publishRulesetVersion } = require("../modules/screening/services/ruleset.service");

// Real provenance, so "this one is AI-generated" is a true statement about the picture and not just
// a label on a stock photo. Both are freely licensed on Wikimedia Commons.
//
// A human-drawn illustration: Louis Wain, d. 1939, public domain.
const HUMAN_IMAGE =
  "https://upload.wikimedia.org/wikipedia/commons/2/29/Picture_of_a_Cat_by_Louis_Wain_%281860%E2%80%931939%29_from_The_Sketch_July_18%2C_1900.png";

// Generated by FLUX.1 — the model is named in the filename, which is the provenance.
const AI_IMAGE =
  "https://upload.wikimedia.org/wikipedia/commons/e/ed/Scenic_Forest_Valley_in_the_Late_Afternoon_%28FLUX.1%29.jpg";

// The dedupe pair still needs bytes that are unique per batch: a fixed URL would hash-match the
// artwork an earlier batch already rejected, so the short circuit would fire on the artwork meant to
// demonstrate the reject path and that path would never be seen. Reusing the two above is safe
// because dedupe only matches previous *rejections*, and neither of them is ever rejected.
const BATCH = Date.now().toString(36);
const PAIR_IMAGE = `https://picsum.photos/seed/modfanart-pair-${BATCH}/800/600`;

// Titles are the steering wheel: the mock adapters read them. Verified behaviour, with
// requireHumanReview disabled:
//   (plain)     -> auto_approved
//   "reject"    -> auto_rejected      (moderation score 0.97)
//   "flag"      -> flagged_manual     (moderation score 0.85)
//   "ai"        -> flagged_manual     (authenticity fail, generator: midjourney)
//   "borderline"-> flagged_manual     (authenticity borderline band)
//   "mockfail"  -> flagged_manual     (stage unavailable — degradation goes to humans)
const ARTWORKS = [
  {
    title: "A hand drawn cat",
    description: "ink on paper, drawn by hand",
    file_url: HUMAN_IMAGE,
    note: "genuinely human-drawn -> auto_approved",
  },
  {
    title: "reject this artwork",
    description: "demo of the reject path",
    file_url: PAIR_IMAGE,
    note: "prohibited content -> auto_rejected",
  },
  {
    title: "an ai generated landscape",
    description: "demo of the authenticity path",
    file_url: AI_IMAGE,
    note: "genuinely AI-generated (FLUX.1) -> flagged_manual, generator recorded",
  },
  {
    title: "totally original artwork",
    description: "same bytes as the rejected one",
    file_url: PAIR_IMAGE,
    note: "resubmission of rejected bytes -> flagged_manual, zero adapter calls",
  },
];

async function resolveOwner(email) {
  if (email) {
    const user = await db
      .selectFrom("users")
      .select(["id", "email"])
      .where("email", "=", email)
      .executeTakeFirst();

    if (user) return user;
    console.warn(`No user with email ${email}; falling back to the first user in the table.`);
  }

  const any = await db.selectFrom("users").select(["id", "email"]).orderBy("created_at").executeTakeFirst();

  if (!any) {
    throw new Error(
      "No users exist yet. Sign in via Postman request 01, then run request 02 (POST /api/auth/sync)."
    );
  }

  return any;
}

/**
 * The seeded platform default sets `requireHumanReview: true`, which is the right default for a
 * fresh install but sends every clean artwork to the queue — so a demo would show nothing but
 * `flagged_manual`. Publishing a version with it off lets the auto-approve and auto-reject paths
 * show themselves. This is a new immutable version, not an edit: the original stays auditable.
 */
async function relaxHumanReviewGate(createdBy) {
  const current = await resolveRuleset(db, { brandId: null });

  if (current?.config?.requireHumanReview === false) {
    console.log(`Ruleset v${current.version} already allows auto-decisions.\n`);
    return;
  }

  const published = await publishRulesetVersion(db, {
    brandId: null,
    config: { ...(current?.config ?? {}), requireHumanReview: false, notifyArtist: false },
    createdBy,
  });

  console.log(
    `Published platform ruleset v${published.version} with requireHumanReview=false ` +
      `(v${current?.version ?? "?"} kept intact).\n`
  );
}

async function main() {
  const owner = await resolveOwner(process.argv[2]);

  console.log(`\nOwner: ${owner.email} (${owner.id})\n`);

  await relaxHumanReviewGate(owner.id);

  const created = [];

  for (const spec of ARTWORKS) {
    const row = await db
      .insertInto("artworks")
      .values({
        creator_id: owner.id,
        title: spec.title,
        description: spec.description,
        file_url: spec.file_url,
        thumbnail_url: spec.file_url,
        status: "moderation_pending",
        moderation_status: "pending",
        views_count: 0,
        favorites_count: 0,
        created_at: sql`NOW()`,
        updated_at: sql`NOW()`,
      })
      .returning(["id", "title"])
      .executeTakeFirst();

    created.push({ ...row, note: spec.note });
    console.log(`  ${row.id}  ${row.title}`);
    console.log(`  ${" ".repeat(36)}${spec.note}\n`);
  }

  console.log("Screen them with:\n");
  for (const row of created) {
    console.log(
      `  curl -s -X POST localhost:5000/api/screening/runs \\\n` +
        `    -H "Authorization: Bearer $TOKEN" -H 'Content-Type: application/json' \\\n` +
        `    -d '{"artworkId":"${row.id}"}'\n`
    );
  }

  console.log("Then read the verdict:\n");
  console.log(
    `  curl -s localhost:5000/api/screening/runs/${created[0].id} -H "Authorization: Bearer $TOKEN" | jq\n`
  );
  console.log(`Postman: set artwork_id = ${created[0].id}\n`);
}

main()
  .catch((error) => {
    console.error("demo-seed failed:", error.message);
    process.exitCode = 1;
  })
  .finally(() => db.destroy());
